### PR TITLE
Release/v3.0.0

### PR DESCRIPTION
**Pull request by rosle**
#37 - Linters and Automated Code Review Setup
#38 - Added sidekiq setup
#40  - Production-ready Docker-based deployment
#43 - Disable instance variable assumption detector for controllers 
#44 - Add missing rspec config for Sidekiq 
#45 - Update transactional fixtures for using in system test
#46 - Add Chrome Headless for system specs 
#47 - [CHORE] Add pull request template to streamline PRs 
#48 - [CHORE] Migrate the PR template to subdirectory .github 
#49 - Minor improvements to the PR template 
#50 - Fix: Incomplete port mapping for all Docker Compose services 
#52 - Fix: Deprecated code for simplecov 
#53 - System Specs config improvement
#54 - CI Improvements

### CODE REVIEW

**Comment by anduonghien** [comment]
@rosle Is it support Rails 5.2 yet?

**Comment by rosle** [comment]
@anduonghien Not yet 😺

**Comment by olivierobert** [comment]
@anduonghien PRs are welcome to support Rails 5.2 😉

**Comment by anduonghien** [comment]
@olivierobert @rosle Already create the issue #56 😄

**Pull request merged**
